name: CI

on:
  push:
    branches: 
    - actions/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: npm

      - name: Install dependencies
        run: npm install
